### PR TITLE
XRPL decoder initial support for some primitive types 

### PR DESCRIPTION
**Pull request by zees-dev**
# Context
This PR adds support for:
- deserializing hex encoded data to relevant primitive types (including arrays and objects)
- `wasm32-unknown-unknown` target architecture support for `xrpl_types` and `xrpl_binary_codec` crates based on `wasm32` feature flag (default dependencies are `std` - i.e. non-wasm)

The primary purpose for this PR is to decode XUMM signed transactions - specifically of the `SignIn` special `TransactionType` - https://docs.xumm.dev/concepts/special-transaction-types
Since the PR can also decode hex data to JSON; it shouldn't take much effort to also deserialize the data to the different transaction types (probably starting off with `TransactionCommon`).

Note: Not all types are supported; support for all `TypeCode` enum variants needs to be added.
Look at the unit tests for more details.

### CODE REVIEW

**Comment by gmosx** [comment]
I would like to suggest this one change. Just remove the Deserializer trait and have it as Deserializer struct to be consistent with the Serializer struct. What do you think?

**Comment by gmosx** [comment]
WASM support is amazing btw :)

**Comment by zees-dev** [comment]
> I would like to suggest this one change. Just remove the Deserializer trait and have it as Deserializer struct to be consistent with the Serializer struct. What do you think?

done; now there is only a single concrete implementation of the `Deserializer` - which i guess does reduce complexity.

Note however: Not all XRPL types are deserializable at the moment (hence why we may not be able to match all the functions in the serializer); this PR adds support for most. A future PR maybe required to support full deserialization.

**Comment by zees-dev** [comment]
FYI added WASM support - but for our use-case we actually need to the `xrpl_binary_codec` crate (and hence the dependent `xrpl_types` crate) in a `no_std` environment.

This will imply use `alloc` and `core` types instead of `std::`.
This PR should probably be refactored to support `no_std` (which would naturally also provide wasm support).
^ this also implies that the `xrpl_types` crate imports need to be refactored too.

**Comment by gmosx** [comment]
> done; now there is only a single concrete implementation of the `Deserializer` - which i guess does reduce complexity.

Thanks!

**Comment by gmosx** [comment]
Can you please also remove this?

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> xrpl_binary_codec/src/lib.rs:3:12
  |
3 | #![feature(once_cell)]
  |            ^^^^^^^^^
```

It's no longer needed.

**Comment by gmosx** [comment]
e.g.

```diff
❯ git diff faacdef10f7a0ff656174
diff --git a/xrpl_binary_codec/src/lib.rs b/xrpl_binary_codec/src/lib.rs
index 2408cb1..9247e88 100644
--- a/xrpl_binary_codec/src/lib.rs
+++ b/xrpl_binary_codec/src/lib.rs
@@ -1,13 +1,12 @@
 //! Binary serialization for XRPL Protocol objects.
 #![allow(stable_features)]
-#![feature(once_cell)]
 
+pub mod deserializer;
 mod error;
 pub mod hash;
 pub mod serialize;
 /// Implements serialization according to <https://xrpl.org/serialization.html>
 pub mod serializer;
-pub mod deserializer;
 pub mod sign;
 
 pub use error::*;
```

**Comment by gmosx** [comment]
@allanbrondumkr would you also like to have a look at this PR? :pray:

**Comment by zees-dev** [comment]
> ```diff
> [feature(once_cell)]
> ```

Removing this results in compilation errors when not on the latest version of rust (nightly).
Specifically fails to compile for me on `rustc 1.69.0-nightly`
Shall we still remove this?

**Comment by gmosx** [comment]
> Removing this results in compilation errors when not on the latest version of rust (nightly). Specifically fails to compile for me on `rustc 1.69.0-nightly` Shall we still remove this?

I think so, I compiled on stable and runs just fine. once_cell was recently added on stable, version 1.70.0, no?

https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html

**Comment by zees-dev** [comment]
> > Removing this results in compilation errors when not on the latest version of rust (nightly). Specifically fails to compile for me on `rustc 1.69.0-nightly` Shall we still remove this?
> 
> I think so, I compiled on stable and runs just fine. once_cell was recently added on stable, version 1.70.0, no?
> 
> https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html

Ok yes, unfortunately we are still on nightly 1.69.0 - so i guess we'll just keep this in our fork.
I'll remove it here 👍

**Comment by gmosx** [comment]
> Ok yes, unfortunately we are still on nightly 1.69.0 - so i guess we'll just keep this in our fork. I'll remove it here 👍

Thank you. The MR looks more or less OK, I will just give @allanbrondumkr a chance to review and merge tomorrow.

Out of curiosity, why do you use the nightly version?

**Comment by zees-dev** [comment]
> > Ok yes, unfortunately we are still on nightly 1.69.0 - so i guess we'll just keep this in our fork. I'll remove it here 👍
> 
> Thank you. The MR looks more or less OK, I will just give @allanbrondumkr a chance to review and merge tomorrow.
> 
> Out of curiosity, why do you use the nightly version?

Nightly generally gets features first - before they go into the stable release train.
It's generally stable enough for us.
Unfortunately in this case we are on a previous version of nightly - which doesn't support this (`once_cell`) feature; our codebase currently relies on this version and would be a bigger hassle to update it :/

**Comment by allanbrondumkr** [comment]
Looks fine to me generally. Not sure if the modules `serializer` and `deserializer` should be `pub`. For serialization, the only way to access it before was through `serialize` module. It is more a question of how much of the library is exposed as an public API, not necessarily a problem as such, I'll leave it to your judgement.

**Comment by gmosx** [comment]
Good point. I will merge for the moment, but I will revisit this.

**Comment by gmosx** [comment]
Merged, thank you @zees-dev

**Pull request merged**
