### PR TITLE
refactor: removed some mod.rs files

### PR DESCRIPTION
**Pull request by gmosx**

### CODE REVIEW

**Comment by gmosx** [comment]
I think mod.rs files where used in older editions of rust, I would like to eventually replace those for consistency. This is a first step cc @allanbrondumkr

**Comment by allanbrondumkr** [comment]
Ok

> I think mod.rs files where used in older editions of rust, I would like to eventually replace those for consistency. This is a first step cc @allanbrondumkr

Ok, that is mainly a matter of style/convention, I think both is fine. Though why do you think it is related to old editions of Rust? Both approaches are valid in Rust, and I think using `mod.rs` is the most common for modules that have submodules.

**Comment by allanbrondumkr** [comment]
> Ok
> 
> > I think mod.rs files where used in older editions of rust, I would like to eventually replace those for consistency. This is a first step cc @allanbrondumkr
> 
> Ok, that is mainly a matter of style/convention, I think both is fine. Though why do you think it is related to old editions of Rust? Both approaches are valid in Rust, and I think using `mod.rs` is the most common for modules that have submodules.

Maybe you are right, I've just seen `mod.rs` used most frequently, but maybe the other approach is the recommended way to do it now.

**Comment by allanbrondumkr** [comment]
I found this reference for it, guess it makes sense https://doc.rust-lang.org/reference/items/modules.html#module-source-filenames. I also don't like that all files are named `mod.rs`, though I like that code related to a module is in one folder, so pros and cons. But it is the recommended way, so that must decide :)

**Pull request merged**
